### ISSUE TITLE
Nil in morganey?

### ISSUE THREAD

**Issue by keddelzz** [keddelzz/Morganey#1]
How is nil in Morganey modeled?

**Comment by rexim** [comment]
Was just browsing your profile and found this. Are you sure that you posted the issue to the right issue tracker? :)

And regarding your question, I belive Morganey is not aware of `Nil` at all. We encode lists like `(a . (b . (c . d)))`. There is no `Nil` for lists. The last element of the list is the second element of the innermost pair. It's not the best solution but it was the quickest one at the time. :D I don't mind to improve that, though.

**Comment by keddelzz** [comment]
You are right, I somehow mixed the two issue-tracker up.

It would be really nice, if Morganey was aware of empty lists.

So, should I create a new issue at your issue-tracker?

**Comment by rexim** [comment]
Of course! Feel free to start any kind of Morganey related conversation by creating an issue in the original issue tracker. :) We are always open for discussion.

**Comment by keddelzz** [comment]
I openend an issue addressing nil in Morganey in the original project of @rexim. So I'll close it here!
